### ISSUE TITLE
Not working when using CtrlPBufTag

### ISSUE THREAD

**Issue by saaguero** [FelikZ/ctrlp-py-matcher#12]
Latest change https://github.com/FelikZ/ctrlp-py-matcher/pull/11 seems like it introduced a bug because it's not filtering correctly the results of a `:CtrlPBufTag`. See:

Without https://github.com/FelikZ/ctrlp-py-matcher/pull/11
![winksyfhjs](https://cloud.githubusercontent.com/assets/2459621/5637965/d1df9c56-95df-11e4-9ee4-6992cd0b1f4a.gif)

With https://github.com/FelikZ/ctrlp-py-matcher/pull/11
Look that after filtering I can't press enter to navigate to the corresponding match in the file.
![wgenecvpsa](https://cloud.githubusercontent.com/assets/2459621/5637966/d2aa522a-95df-11e4-8740-be0f405b5921.gif)

**Comment by FelikZ** [comment]
Sorry I didn't have time right now, use those old version until it will be fixed - there is no much difference since.
