### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jlebar** [FelikZ/ctrlp-py-matcher#23]
Hi, I'm interested in forking this project, but I can't do so at the moment because this code doesn't have a license.  Would you mind adding an explicit license to this project?

Thanks!

**Comment by jlebar** [comment]
Ah, now I see that there's a license in the help file.  That's good enough for me to fork this, but leaving this open in case you want to add a proper LICENSE file to the repo.

**Comment by FelikZ** [comment]
Feel free to fork

**Comment by jlebar** [comment]
Did you mean to add the MIT license with the Google/Angular JS copyright?

> Copyright (c) 2010-2015 Google, Inc. http://angularjs.org

**Comment by jlebar** [comment]
https://github.com/jlebar/ctrlp-py-matcher/commit/e5f15ae97b1cab39824d43f27fa49039b232d525 if you want to see what I'm up to.  :)

**Comment by FelikZ** [comment]
@jlebar :) thanks, fixed.
