### ISSUE TITLE
Is it possible to comply to `g:ctrlp_match_current_file`?

### ISSUE THREAD

**Issue by kassio** [FelikZ/ctrlp-py-matcher#26]
One of the features that I like most on ctrlp is that it can ignore the current file on its result list. Is it possible to `ctrlp-py-matcher` do the same?

Thank you!

**Comment by FelikZ** [comment]
You mean current active buffer?

**Comment by kassio** [comment]
Yes.

**Comment by FelikZ** [comment]
We need to have a look to the source of base matcher, I believe there is nothing impossible but could be tricky. I can't promise any dates on this but will keep it mind.

**Comment by kassio** [comment]
Thank you a lot for the effort!

**Comment by mrsipan** [comment]
Open PR addressing this issue: https://github.com/FelikZ/ctrlp-py-matcher/pull/31

**Comment by FelikZ** [comment]
@kassio if you remove `g:ctrlp_match_current_file` setting from .vimrc it will work for you, thanks to @mrsipan .

**Comment by kassio** [comment]
thank you!
