### ISSUE TITLE
Never Finds Any Results

### ISSUE THREAD

**Issue by xanderdunn** [FelikZ/ctrlp-py-matcher#27]
I'm running neovim's 0.1.4 release with 
```
Plug 'FelikZ/ctrlp-py-matcher'              " faster ctrlp index searcher
```
and
```
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
```

When first opening ctrl-p, I see the default results, but as soon as I type any character to perform any search, I get the "NO ENTRIES" message.  Functionality returns to normal (just slow) when I comment out the `ctrlp_match_func` line above.

I just ran my plugin manager's updater to make sure I'm running latest ctrlp-py-matcher.

**Comment by FelikZ** [comment]
Hi @xanderdunn, I didn't tested plugin with neovim for a while, it might be that it is broken since some of releases.

**Comment by swistak35** [comment]
I can confirm that it does has this bug on neovim 0.1.4 installed on Arch Linux, but no problems on vim (I have shared vimrc config). I'm not pythonista, but let me know if I can help in any way

**Comment by FelikZ** [comment]
Works for me in neovim 1.5.0-dev.
