### ISSUE TITLE
Fix the case-(in)sensitivity related issues in the matcher

### ISSUE THREAD

**Issue by romix** [FelikZ/ctrlp-py-matcher#29]
The matcher currently seems to be always lower the strings, before it does the actual matching.

This is fine in most cases. But sometimes it leads to strange results. For example, if you are in a regex mode and you look just for a regex which is a simple string "MySubstring" (not the two uppercase letters), you won't get any results, even if the actual original line contains it. This happens, because the regex is case-sensitive, but the lines it is being matched against are not, since they are lowered. 

You should probably either avoid lowering lines in some cases. 
Or you should use the case insensitive matching mode for regexes, which can be easily done by replacing the current:

```python
prog = re.compile(regex)
```
by
```python
prog = re.compile(regex, re.IGNORECASE)
```

**Comment by FelikZ** [comment]
Hi @romix,

The reason why current matching is lowering everything is because it works **much** faster then with IGNORECASE flag.

I suggest to convert user input to lower case - in that case your example will find something.

**Comment by romix** [comment]
@FelikZ OK, so you do it for performance reasons. I see.

In this case, how about lowercasing the search string/regex before you compile it? I think it should be done by your plugin just before the `re.compile` line. Of course you could ask the users to do so before they call your plugin, but IMHO this would be wrong, because your plugin is supposed to be a drop-in replacement for CtrlP matching functions. And CtrlP does not have a requirement to lowercase the search strings/regexes.

If you decide not to lowercase the search string/regex and expect users to do so before a call, I'd suggest to clearly document this. I.e. that different from the standard CtrlP matching function, your plugin expects all search strings/regexes to be in the lowercase to function properly.

**Comment by FelikZ** [comment]
@romix I think this is good idea to do both - force lower case the query and document this. Again, idea behind this plugin is performance. If you know the way how to do insensitive searches with the same speed - it would be nice to share it :)

**Comment by romix** [comment]
@FelikZ Yes, I've run some benchmarks and re.IGNORECASE is much slower in many cases.
But another approach that I mentioned seems to work just fine, namely lowercasing the regex before you call re.compile on it. It does not lead to performance degradation and it finds proper strings.
Would do you think about adding this change to your code?

**Comment by FelikZ** [comment]
@romix that sounds logical to me now, so I agree with that.
