### ISSUE TITLE
Doesn't work with Neovim

### ISSUE THREAD

**Issue by osa1** [FelikZ/ctrlp-py-matcher#30]
Is it too hard to fix? See https://github.com/ctrlpvim/ctrlp.vim/issues/262.

**Comment by FelikZ** [comment]
Works for me with latest available neovim (1.5.0-dev).

I have used instructions from here:
https://github.com/neovim/neovim/wiki/Installing-Neovim

And then [this post](https://github.com/Shougo/deoplete.nvim/issues/223#issuecomment-197117175) to fix python stuff.
