### ISSUE TITLE
Accept filtering buffer by number

### ISSUE THREAD

**Issue by vimeitor** [FelikZ/ctrlp-py-matcher#36]
Hello!

Firstly, thank you for the plugin. Works wonderfully. I have one small problem, however. When displaying the available buffers, ctrlp attaches a number next to the filename. When using the default matcher, you can filter the buffers by said number; however, your matcher does not. Do you think it would be possible to allow filtering by number?

Thank you :)

**Comment by FelikZ** [comment]
@vimeitor hello! Not sure about it. This numbers attached by ctrl-p in some different part then matcher. Maybe this can be overridden but require some time for investigation that I do not have, sry.
