### ISSUE TITLE
Inconsistency with original CtrlP output

### ISSUE THREAD

**Issue by sergey-vlasov** [FelikZ/ctrlp-py-matcher#5]
Hi. The performance is great but py-matcher result sorting is different. Different in a bad way. Most of the time the needed file would be among the first results when using CtrlP, but with py-matcher I often need to scroll down or give be more accurate input. Is it possible to make py-matcher to match the results to the original CtrlP output?

original output:
![orig](https://cloud.githubusercontent.com/assets/717109/3146487/2f5bbd86-ea48-11e3-9620-d1fafead356e.png)

 py-matcher output:
![pymatcher](https://cloud.githubusercontent.com/assets/717109/3146489/38b265b0-ea48-11e3-8ae4-de22a7a79cf0.png)

**Comment by mrafcho001** [comment]
For what its worth, py-matcher sorting is much better on my project. Rarely need to type more than 3 letters to get the file I want. With default CtrlP I need to go 6+ letters.
