### ISSUE TITLE
Matcher custom sorting

### ISSUE THREAD

**Issue by kshenoy** [FelikZ/ctrlp-py-matcher#6]
Is there a way to specify the manner in which the output is to be sorted?
For eg. I want to sort in increasing order of length so that the file/buffer with the shortest possible name is nearest.

Also, does the matcher work across all the different "extensions" or only for files?
For that matter, how do I find out for sure if ctrlp is using the matcher or not?

Thanks

**Comment by FelikZ** [comment]
This should work since one of the previous releases.
